name: aca-flask
dependencies:
- click=6.6=py27_0
- flask=0.11=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_1
- markupsafe=0.23=py27_2
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=22.0.5=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.11.9=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - alembic==0.8.6
  - blinker==1.4
  - dominate==2.2.0
  - flask-bootstrap==3.3.5.7
  - flask-mail==0.9.1
  - flask-migrate==1.8.0
  - flask-moment==0.5.1
  - flask-script==2.0.5
  - flask-sqlalchemy==2.1
  - flask-wtf==0.12
  - mako==1.0.4
  - python-editor==1.0
  - sqlalchemy==1.0.12
  - visitor==0.1.2
  - wtforms==2.1

